### ISSUE TITLE
"Civic Insight" name is problematic

### ISSUE THREAD

**Issue by ajb** [MicrosoftTCE/civic-graph-node#25]
cf http://civicinsight.com/

**Comment by fkh** [comment]
Just to be more explicit, Civic Insight is the name of an existing civic tech company. It would be great if this project didn't conflict with the name of that existing company, since both are hopefully going to be really popular!

**Comment by adysevy** [comment]
We changed the name of the application to "Civic Graph" ;)

**Comment by ajb** [comment]
Awesome, thanks for acknowledging and resolving.

On Fri, Mar 6, 2015 at 3:59 PM, adysevy notifications@github.com wrote:

> Closed #25 https://github.com/microsoftny/athena-civic/issues/25.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/microsoftny/athena-civic/issues/25#event-247783128.

## 

Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by fkh** [comment]
+1 for being great about this.

On Fri, Mar 6, 2015 at 4:03 PM, Adam Becker notifications@github.com
wrote:

> Awesome, thanks for acknowledging and resolving.
> 
> On Fri, Mar 6, 2015 at 3:59 PM, adysevy notifications@github.com wrote:
> 
> > Closed #25 https://github.com/microsoftny/athena-civic/issues/25.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/microsoftny/athena-civic/issues/25#event-247783128.
> 
> ## 
> 
> Adam Becker
> (951) 9-BECKER
> @AdamJacobBecker
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/microsoftny/athena-civic/issues/25#issuecomment-77635309
> .

## 

Frank Hebbert
OpenPlans | http://openplans.org | 720 432-2378 | @fkh
