### ISSUE TITLE
link to the live site!

### ISSUE THREAD

**Issue by afeld** [MicrosoftTCE/civic-graph-node#29]
I don't know where to find it :confused:

**Comment by afeld** [comment]
http://civicinsight.azurewebsites.net/

**Comment by sugaroverflow** [comment]
[bit.ly/athenacivic](bit.ly/athenacivic) is the shorter link

**Comment by afeld** [comment]
It's easy to miss in the README (I hadn't seen it at first glance)... would be easier to see added here:

![microsoftny_athena-civic](https://cloud.githubusercontent.com/assets/86842/6320652/7bb277a8-bab1-11e4-99da-abb6a74e967c.png)

Thanks!

**Comment by sugaroverflow** [comment]
Thanks @afeld 
@KenChan23 can edit the title + description to add the link from the MS account
